### ISSUE TITLE
Add support for Jump to Definition 

### ISSUE THREAD

**Issue by paulcsmith** [crystal-lang-tools/vscode-crystal-lang#42] opened 2017-12-13 19:55 UTC
I'm loving the plugin so far. It would be wonderful if it could also support Jump to Definition so I could jump to a class or method definition in the project.

Thanks for the project, and thanks for considering this feature.

**Comment by faustinoaq** [comment] 2017-12-13 21:36
@paulcsmith Thank for your comment!

Go to Definition already work just methods. Modules or clases doesn't work due crystal doesn't support it yet. See https://github.com/crystal-lang/crystal/issues/4941

_Still a bit unstable, sometimes doesn't work_ ⚠️ 

You can enable go to method definition using:

```json
{
  "crystal-lang.implementations": true
}
```

https://github.com/crystal-lang-tools/vscode-crystal-lang/wiki/Settings#implementations

If you are in a custom project where you specify all requires inside a main file then you need to use:

https://github.com/crystal-lang-tools/vscode-crystal-lang/wiki/Settings#mainfile

```json
{
  "crystal-lang.mainFile": "${workspaceRoot}/src/mymainfile.cr"
}
```

![go to](https://i.imgur.com/FDrEP7E.gif)

(Older version _Peek implementation_ command has been removed on latest versions)

![kemal go to](https://i.imgur.com/Fb0HVc6.gif)

**Comment by minkir014** [comment] 2019-06-17 20:11
But as I see now that issue is fixed by a PR. Can you support that now??

**Comment by iambudi** [comment] 2019-11-16 15:04
When jump to definition throws the following error:

```bash
[Info  - 9:53:45 PM] Scry is looking into your code...
[Error - 9:53:54 PM] A error was found while searching implementations
Unexpected char 'U' at 1:1
Usage: crystal tool implementations [options] [programfile] [--] [arguments]
```

**Comment by faustinoaq** [comment] 2020-03-31 08:52
Hi, @minkir014 @iambudi This extension uses the output provided by `crystal tool` CLI, so if the feature finds an error it's because crystal was designed that way, there is some workaround using a dynamic code analyzer based on javascript or something similar

[Scry](https://github.com/crystal-lang-tools/scry) has some nice features but is in a very experimental state yet. It also uses crystal CLI, so it is an issue and it requires the full updated implementation of [Language Server Protocol](https://microsoft.github.io/language-server-protocol/).

Right now I'm fixing some issues on Node.js backend of this extension, I'll figure out a way to solve this issue.

Cheers!

**Comment by paulcsmith** [comment] 2020-04-02 22:58
Thanks @faustinoaq!!

**Comment by Narven** [comment] 2023-05-29 10:23
What is the current status of this?

On my side I don't see this work in any way currently. With peek, mouse click or anything.

I would say this is a pretty standard way to navigate code in the last 10 years, it pretty much renders useless any kind of editor/ide if it does not have it.

I'm currently running:
```bash
$ crystal -v
Crystal 1.8.2 (2023-05-09)

LLVM: 15.0.7
Default target: x86_64-apple-macosx 
```

What do we need to do to make this a top priority? and/or help?

**Comment by iambudi** [comment] 2023-05-30 14:31
@Narven you might try this [alternative](https://github.com/elbywan/crystalline)

**Comment by Narven** [comment] 2023-05-30 15:15
Thanks @iambudi, will try that.

**Comment by nobodywasishere** [comment] 2023-12-06 04:07
This should work with v0.9.0-alpha.1, though it's reliant on the `crystal tool implementations` CLI tool. This can be unreliable when working on a libraries internals and I'm not sure why - when working on an executable/app where everything gets compiled it works well.

**Closed** 2024-02-02 03:01 UTC
Labels: enhancement, help wanted
