### ISSUE TITLE
[Feature] Being able to Ctrl-click a class or method

### ISSUE THREAD

**Issue by qequ** [crystal-lang-tools/vscode-crystal-lang#164] opened 2023-05-14 21:21 UTC
Similar to other languages vscode supports it would be great to have a feature that allows press Ctrl and left click and move you to the location of the class/method selected

**Comment by nobodywasishere** [comment] 2023-05-19 07:02
This may be a duplicate of #42

**Closed** 2023-06-01 14:33 UTC
